// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6mGDKGC25nyACBQT-hshY2AQbxirsq6k',
    appId: '1:409452439863:web:36236233cb7df2184152b2',
    messagingSenderId: '409452439863',
    projectId: 'realizealpha',
    authDomain: 'realizealpha.firebaseapp.com',
    storageBucket: 'realizealpha.firebasestorage.app',
    measurementId: 'G-Y5TTR48RBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSSNNKbDh7uvlOhlfW__xuiuZi0vkLqw',
    appId: '1:409452439863:android:478a34d114a866ee4152b2',
    messagingSenderId: '409452439863',
    projectId: 'realizealpha',
    storageBucket: 'realizealpha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-kVrcB5cdLifr6SkUBHD1YXZKxgGt1bo',
    appId: '1:409452439863:ios:379ee6f6ee12a33e4152b2',
    messagingSenderId: '409452439863',
    projectId: 'realizealpha',
    storageBucket: 'realizealpha.firebasestorage.app',
    iosBundleId: 'com.cidevelop.robinhoodOptionsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-kVrcB5cdLifr6SkUBHD1YXZKxgGt1bo',
    appId: '1:409452439863:ios:379ee6f6ee12a33e4152b2',
    messagingSenderId: '409452439863',
    projectId: 'realizealpha',
    storageBucket: 'realizealpha.firebasestorage.app',
    iosBundleId: 'com.cidevelop.robinhoodOptionsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6mGDKGC25nyACBQT-hshY2AQbxirsq6k',
    appId: '1:409452439863:web:1dd4c1744757e6bb4152b2',
    messagingSenderId: '409452439863',
    projectId: 'realizealpha',
    authDomain: 'realizealpha.firebaseapp.com',
    storageBucket: 'realizealpha.firebasestorage.app',
    measurementId: 'G-YEWHE2RF85',
  );

}