// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-VbuIEHsXYk5-1sRVSzHRQnM2rfusdQ',
    appId: '1:507549221555:web:ba8c1c83c0ff28c315e6c6',
    messagingSenderId: '507549221555',
    projectId: 'investiomanus',
    authDomain: 'investiomanus.firebaseapp.com',
    storageBucket: 'investiomanus.appspot.com',
    measurementId: 'G-HY9MVQQGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCll0SsOLABNtLmLZptvU3X5WC0XBSxkZk',
    appId: '1:507549221555:android:5e4509b8b9a595aa15e6c6',
    messagingSenderId: '507549221555',
    projectId: 'investiomanus',
    storageBucket: 'investiomanus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4fs3KqI8JMZncfixXL8CAX0QLbKR7LY',
    appId: '1:507549221555:ios:565c1fedf6f01a3815e6c6',
    messagingSenderId: '507549221555',
    projectId: 'investiomanus',
    storageBucket: 'investiomanus.appspot.com',
    iosClientId: '507549221555-ie4a6fk5auvqiiitp1bbj6iqdl9jm118.apps.googleusercontent.com',
    iosBundleId: 'com.cidevelop.robinhoodOptionsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi4fs3KqI8JMZncfixXL8CAX0QLbKR7LY',
    appId: '1:507549221555:ios:ee3b06f863386d1715e6c6',
    messagingSenderId: '507549221555',
    projectId: 'investiomanus',
    storageBucket: 'investiomanus.appspot.com',
    iosClientId: '507549221555-u5ck1erqk1kq1vgkher9qesf4ev6neck.apps.googleusercontent.com',
    iosBundleId: 'com.cidevelop.robinhoodOptionsMobile.RunnerTests',
  );
}
