import 'package:robinhood_options_mobile/model/backtesting_models.dart';

/// Pre-built strategy templates for backtesting
class BacktestingDefaults {
  static final List<BacktestTemplate> defaultTemplates = [
    BacktestTemplate(
      id: 'default_momentum_master',
      name: 'Momentum Master',
      description: 'Captures strong price moves using RSI, MACD, and Volume.',
      config: BacktestConfig(
        symbol: 'SPY',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': true, // RSI
          'marketDirection': false,
          'volume': true,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 15.0,
        stopLossPercent: 5.0,
        trailingStopEnabled: true,
        trailingStopPercent: 3.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_mean_reversion',
      name: 'Mean Reversion',
      description:
          'Trades reversals from overbought/oversold conditions using Bollinger Bands and RSI.',
      config: BacktestConfig(
        symbol: 'QQQ',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': true, // RSI
          'marketDirection': false,
          'volume': false,
          'macd': false,
          'bollingerBands': true,
          'stochastic': true,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': true,
        },
        takeProfitPercent: 8.0,
        stopLossPercent: 4.0,
        trailingStopEnabled: false,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_trend_follower',
      name: 'Trend Follower',
      description: 'Rides established trends using Moving Averages and ADX.',
      config: BacktestConfig(
        symbol: 'IWM',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': true, // SMA crossovers
          'volume': false,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': true, // For volatility adjustment
          'obv': true,
          'vwap': false,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 20.0,
        stopLossPercent: 8.0,
        trailingStopEnabled: true,
        trailingStopPercent: 5.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_volatility_breakout',
      name: 'Volatility Breakout',
      description:
          'Enters trades when volatility expands using ATR and Bollinger Bands.',
      config: BacktestConfig(
        symbol: 'NVDA',
        startDate: DateTime.now().subtract(const Duration(days: 90)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': false,
          'volume': true,
          'macd': false,
          'bollingerBands': true,
          'stochastic': false,
          'atr': true,
          'obv': false,
          'vwap': true,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 12.0,
        stopLossPercent: 3.0,
        trailingStopEnabled: true,
        trailingStopPercent: 2.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_conservative_growth',
      name: 'Conservative Growth',
      description:
          'Low-risk strategy focusing on steady gains with tight risk management.',
      config: BacktestConfig(
        symbol: 'DIA',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': true,
          'volume': false,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 5.0,
        stopLossPercent: 2.0,
        trailingStopEnabled: true,
        trailingStopPercent: 1.5,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_golden_cross',
      name: 'Golden Cross',
      description:
          'Classic long-term trend strategy using 50/200 SMA crossover.',
      config: BacktestConfig(
        symbol: 'SPY',
        startDate: DateTime.now().subtract(const Duration(days: 730)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': false,
          'marketDirection': true, // SMA
          'volume': true,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': true, // Confirm trend strength
          'williamsR': false,
        },
        smaPeriodFast: 50,
        smaPeriodSlow: 200,
        takeProfitPercent: 25.0,
        stopLossPercent: 10.0,
        trailingStopEnabled: true,
        trailingStopPercent: 5.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_macd_crossover',
      name: 'MACD Crossover',
      description:
          'Momentum strategy based on MACD line crossing the signal line.',
      config: BacktestConfig(
        symbol: 'AAPL',
        startDate: DateTime.now().subtract(const Duration(days: 180)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': false,
          'marketDirection': false,
          'volume': false,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 5.0,
        stopLossPercent: 2.0,
        trailingStopEnabled: false,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_rsi_scalper',
      name: 'RSI Scalper',
      description:
          'Short-term strategy targeting quick reversals using RSI on 15m timeframe.',
      config: BacktestConfig(
        symbol: 'TSLA',
        startDate: DateTime.now().subtract(const Duration(days: 30)),
        endDate: DateTime.now(),
        interval: '15m',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': true, // RSI
          'marketDirection': false,
          'volume': true,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        rsiPeriod: 7, // Faster RSI for scalping
        takeProfitPercent: 3.0,
        stopLossPercent: 1.5,
        trailingStopEnabled: true,
        trailingStopPercent: 1.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_bollinger_squeeze',
      name: 'Bollinger Squeeze',
      description:
          'Captures explosive moves following periods of low volatility.',
      config: BacktestConfig(
        symbol: 'AMD',
        startDate: DateTime.now().subtract(const Duration(days: 180)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': false,
          'volume': true,
          'macd': false,
          'bollingerBands': true,
          'stochastic': false,
          'atr': true, // To measure volatility expansion
          'obv': false,
          'vwap': false,
          'adx': true, // To confirm trend strength after breakout
          'williamsR': false,
        },
        takeProfitPercent: 10.0,
        stopLossPercent: 4.0,
        trailingStopEnabled: true,
        trailingStopPercent: 3.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_vwap_pullback',
      name: 'VWAP Pullback',
      description:
          'Intraday strategy buying dips to the Volume Weighted Average Price.',
      config: BacktestConfig(
        symbol: 'MSFT',
        startDate: DateTime.now().subtract(const Duration(days: 60)),
        endDate: DateTime.now(),
        interval: '15m',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': true, // Ensure we are in an uptrend
          'volume': true,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': true,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 2.0,
        stopLossPercent: 1.0,
        trailingStopEnabled: false,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_stochastic_swing',
      name: 'Stochastic Swing',
      description:
          'Swing trading strategy using Stochastic Oscillator for entry signals.',
      config: BacktestConfig(
        symbol: 'GOOGL',
        startDate: DateTime.now().subtract(const Duration(days: 180)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': false,
          'marketDirection': true, // Filter with trend
          'volume': false,
          'macd': false,
          'bollingerBands': false,
          'stochastic': true,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 7.0,
        stopLossPercent: 3.5,
        trailingStopEnabled: true,
        trailingStopPercent: 2.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_crypto_proxy_momentum',
      name: 'Crypto Proxy Momentum',
      description:
          'High-volatility momentum strategy designed for crypto-correlated stocks.',
      config: BacktestConfig(
        symbol: 'COIN',
        startDate: DateTime.now().subtract(const Duration(days: 90)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': true,
          'marketDirection': false,
          'volume': true,
          'macd': true,
          'bollingerBands': true,
          'stochastic': false,
          'atr': true,
          'obv': true,
          'vwap': false,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 15.0,
        stopLossPercent: 7.0,
        trailingStopEnabled: true,
        trailingStopPercent: 5.0,
      ),
      createdAt: DateTime.now(),
    ),
  ];
}
