import 'package:robinhood_options_mobile/model/backtesting_models.dart';

/// Pre-built strategy templates for backtesting
class BacktestingDefaults {
  static final List<BacktestTemplate> defaultTemplates = [
    BacktestTemplate(
      id: 'default_momentum_master',
      name: 'Momentum Master',
      description: 'Captures strong price moves using RSI, MACD, and Volume.',
      config: BacktestConfig(
        symbol: 'SPY',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': true, // RSI
          'marketDirection': false,
          'volume': true,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 15.0,
        stopLossPercent: 5.0,
        trailingStopEnabled: true,
        trailingStopPercent: 3.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_mean_reversion',
      name: 'Mean Reversion',
      description:
          'Trades reversals from overbought/oversold conditions using Bollinger Bands and RSI.',
      config: BacktestConfig(
        symbol: 'QQQ',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': true, // RSI
          'marketDirection': false,
          'volume': false,
          'macd': false,
          'bollingerBands': true,
          'stochastic': true,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': true,
        },
        takeProfitPercent: 8.0,
        stopLossPercent: 4.0,
        trailingStopEnabled: false,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_trend_follower',
      name: 'Trend Follower',
      description: 'Rides established trends using Moving Averages and ADX.',
      config: BacktestConfig(
        symbol: 'IWM',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': true, // SMA crossovers
          'volume': false,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': true, // For volatility adjustment
          'obv': true,
          'vwap': false,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 20.0,
        stopLossPercent: 8.0,
        trailingStopEnabled: true,
        trailingStopPercent: 5.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_volatility_breakout',
      name: 'Volatility Breakout',
      description:
          'Enters trades when volatility expands using ATR and Bollinger Bands.',
      config: BacktestConfig(
        symbol: 'NVDA',
        startDate: DateTime.now().subtract(const Duration(days: 90)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': false,
          'volume': true,
          'macd': false,
          'bollingerBands': true,
          'stochastic': false,
          'atr': true,
          'obv': false,
          'vwap': true,
          'adx': true,
          'williamsR': false,
        },
        takeProfitPercent: 12.0,
        stopLossPercent: 3.0,
        trailingStopEnabled: true,
        trailingStopPercent: 2.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_conservative_growth',
      name: 'Conservative Growth',
      description:
          'Low-risk strategy focusing on steady gains with tight risk management.',
      config: BacktestConfig(
        symbol: 'DIA',
        startDate: DateTime.now().subtract(const Duration(days: 365)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': true,
          'momentum': false,
          'marketDirection': true,
          'volume': false,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 5.0,
        stopLossPercent: 2.0,
        trailingStopEnabled: true,
        trailingStopPercent: 1.5,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_golden_cross',
      name: 'Golden Cross',
      description:
          'Classic long-term trend strategy using 50/200 SMA crossover.',
      config: BacktestConfig(
        symbol: 'SPY',
        startDate: DateTime.now().subtract(const Duration(days: 730)),
        endDate: DateTime.now(),
        interval: '1d',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': false,
          'marketDirection': true, // SMA
          'volume': true,
          'macd': false,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': true, // Confirm trend strength
          'williamsR': false,
        },
        smaPeriodFast: 50,
        smaPeriodSlow: 200,
        takeProfitPercent: 25.0,
        stopLossPercent: 10.0,
        trailingStopEnabled: true,
        trailingStopPercent: 5.0,
      ),
      createdAt: DateTime.now(),
    ),
    BacktestTemplate(
      id: 'default_macd_crossover',
      name: 'MACD Crossover',
      description:
          'Momentum strategy based on MACD line crossing the signal line.',
      config: BacktestConfig(
        symbol: 'AAPL',
        startDate: DateTime.now().subtract(const Duration(days: 180)),
        endDate: DateTime.now(),
        interval: '1h',
        enabledIndicators: {
          'priceMovement': false,
          'momentum': false,
          'marketDirection': false,
          'volume': false,
          'macd': true,
          'bollingerBands': false,
          'stochastic': false,
          'atr': false,
          'obv': false,
          'vwap': false,
          'adx': false,
          'williamsR': false,
        },
        takeProfitPercent: 5.0,
        stopLossPercent: 2.0,
        trailingStopEnabled: false,
      ),
      createdAt: DateTime.now(),
    ),
  ];
}
