import 'package:robinhood_options_mobile/model/futures_strategy_config.dart';

class FuturesStrategyTemplate {
  final String id;
  final String name;
  final String description;
  final FuturesStrategyConfig config;
  final DateTime createdAt;
  final DateTime? lastUsedAt;

  FuturesStrategyTemplate({
    required this.id,
    required this.name,
    required this.description,
    required this.config,
    required this.createdAt,
    this.lastUsedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'description': description,
        'config': config.toJson(),
        'createdAt': createdAt.toIso8601String(),
        'lastUsedAt': lastUsedAt?.toIso8601String(),
      };

  factory FuturesStrategyTemplate.fromJson(Map<String, dynamic> json) {
    return FuturesStrategyTemplate(
      id: json['id'] as String,
      name: json['name'] as String,
      description: json['description'] as String,
      config: FuturesStrategyConfig.fromJson(
        Map<String, dynamic>.from(json['config'] as Map),
      ),
      createdAt: DateTime.parse(json['createdAt'] as String),
      lastUsedAt: json['lastUsedAt'] != null
          ? DateTime.parse(json['lastUsedAt'] as String)
          : null,
    );
  }
}

class FuturesStrategyDefaults {
  static final List<FuturesStrategyTemplate> defaultTemplates = [
    FuturesStrategyTemplate(
      id: 'futures_trend_following',
      name: 'Trend Following',
      description:
          'Follows sustained directional moves using comprehensive technical indicators with high conviction requirements.',
      config: FuturesStrategyConfig(
        interval: '1h',
        minSignalStrength: 85.0,
        requireAllIndicatorsGreen: false,
        contractIds: ['ES', 'NQ', 'YM'],
        tradeQuantity: 1,
        maxContracts: 3,
        maxNotional: 250000.0,
        maxDailyLoss: 2000.0,
        enabledIndicators: {
          'priceMovement': true,
          'momentum': true,
          'marketDirection': true,
          'volume': true,
          'macd': true,
          'bollingerBands': true,
          'stochastic': true,
          'atr': true,
          'obv': true,
          'vwap': true,
          'adx': true,
          'williamsR': true,
          'ichimoku': true,
          'cci': true,
          'parabolicSar': true,
          'roc': true,
          'chaikinMoneyFlow': true,
          'fibonacciRetracements': true,
          'pivotPoints': true,
        },
        indicatorReasons: {
          'priceMovement': 'Price action analysis for trend confirmation.',
          'momentum': 'RSI analysis for momentum validation.',
          'marketDirection': 'Market trend direction alignment.',
          'volume': 'Volume confirmation for institutional participation.',
          'macd': 'Trend following momentum oscillator.',
          'bollingerBands': 'Volatility bands for trend strength.',
          'stochastic': 'Momentum oscillator for overbought/oversold levels.',
          'atr': 'Volatility measurement for position sizing.',
          'obv': 'Volume flow analysis for accumulation/distribution.',
          'vwap': 'Institutional price level reference.',
          'adx': 'Trend strength measurement.',
          'williamsR': 'Momentum oscillator for reversal signals.',
          'ichimoku': 'Comprehensive trend and support/resistance system.',
          'cci': 'Cyclical trend analysis.',
          'parabolicSar': 'Trend following with stop levels.',
          'roc': 'Rate of change momentum indicator.',
          'chaikinMoneyFlow': 'Money flow analysis.',
          'fibonacciRetracements': 'Key support/resistance levels.',
          'pivotPoints': 'Daily pivot levels for trend context.',
        },
        enableDynamicPositionSizing: true,
        riskPerTrade: 0.02,
        stopLossPct: 2.0,
        takeProfitPct: 8.0,
        trailingStopEnabled: true,
        trailingStopAtrMultiplier: 2.5,
        autoExitEnabled: true,
        autoExitBufferMinutes: 15,
        allowContractRollover: true,
        skipRiskGuard: false,
        multiIntervalAnalysis: true,
      ),
      createdAt: DateTime.now(),
    ),
    FuturesStrategyTemplate(
      id: 'futures_breakout',
      name: 'Breakout Momentum',
      description:
          'Targets volatility breakouts with volume confirmation and momentum acceleration.',
      config: FuturesStrategyConfig(
        interval: '30m',
        minSignalStrength: 75.0,
        requireAllIndicatorsGreen: false,
        contractIds: ['ES', 'NQ', 'CL', 'GC'],
        tradeQuantity: 1,
        maxContracts: 2,
        maxNotional: 150000.0,
        maxDailyLoss: 1500.0,
        enabledIndicators: {
          'priceMovement': true,
          'volume': true,
          'bollingerBands': true,
          'atr': true,
          'momentum': true,
          'stochastic': true,
          'macd': true,
          'adx': true,
          'roc': true,
          'vwap': true,
        },
        indicatorReasons: {
          'priceMovement': 'Breakout pattern detection.',
          'volume': 'Volume spike confirmation.',
          'bollingerBands': 'Volatility expansion signals.',
          'atr': 'Volatility-based position sizing.',
          'momentum': 'RSI confirmation of momentum shift.',
          'stochastic': 'Overbought/oversold momentum levels.',
          'macd': 'Momentum crossover signals.',
          'adx': 'Trend strength for breakout validity.',
          'roc': 'Rate of change acceleration.',
          'vwap': 'Breakout above key institutional levels.',
        },
        enableDynamicPositionSizing: true,
        riskPerTrade: 0.015,
        stopLossPct: 1.5,
        takeProfitPct: 6.0,
        trailingStopEnabled: true,
        trailingStopAtrMultiplier: 2.0,
        autoExitEnabled: true,
        autoExitBufferMinutes: 10,
        allowContractRollover: false,
        skipRiskGuard: false,
        multiIntervalAnalysis: false,
      ),
      createdAt: DateTime.now(),
    ),
    FuturesStrategyTemplate(
      id: 'futures_mean_reversion',
      name: 'Mean Reversion',
      description: 'Exploits price extremes with RSI and Bollinger Band mean reversion signals.',
      config: FuturesStrategyConfig(
        interval: '1h',
        minSignalStrength: 70.0,
        requireAllIndicatorsGreen: true,
        contractIds: ['ES', 'NQ', 'RTY'],
        tradeQuantity: 1,
        maxContracts: 2,
        maxNotional: 100000.0,
        maxDailyLoss: 1000.0,
        enabledIndicators: {
          'bollingerBands': true,
          'momentum': true,
          'stochastic': true,
          'williamsR': true,
          'cci': true,
          'vwap': true,
          'volume': true,
        },
        indicatorReasons: {
          'bollingerBands': 'Mean reversion from band extremes.',
          'momentum': 'RSI oversold/overbought levels.',
          'stochastic': 'Stochastic oscillator extremes.',
          'williamsR': 'Williams %R oversold signals.',
          'cci': 'CCI divergence and extreme levels.',
          'vwap': 'Reversion to value levels.',
          'volume': 'Volume confirmation of reversal.',
        },
        enableDynamicPositionSizing: true,
        riskPerTrade: 0.02,
        stopLossPct: 1.0,
        takeProfitPct: 3.0,
        trailingStopEnabled: false,
        autoExitEnabled: true,
        autoExitBufferMinutes: 30,
        allowContractRollover: false,
        skipRiskGuard: false,
        multiIntervalAnalysis: false,
      ),
      createdAt: DateTime.now(),
    ),
    FuturesStrategyTemplate(
      id: 'futures_momentum_reversal',
      name: 'Momentum Reversal',
      description: 'Captures momentum fade and reversal patterns using multiple momentum indicators.',
      config: FuturesStrategyConfig(
        interval: '30m',
        minSignalStrength: 75.0,
        requireAllIndicatorsGreen: false,
        contractIds: ['ES', 'NQ', 'YM', 'CL'],
        tradeQuantity: 1,
        maxContracts: 3,
        maxNotional: 200000.0,
        maxDailyLoss: 1800.0,
        enabledIndicators: {
          'momentum': true,
          'roc': true,
          'macd': true,
          'stochastic': true,
          'williamsR': true,
          'cci': true,
          'volume': true,
          'adx': true,
          'priceMovement': true,
        },
        indicatorReasons: {
          'momentum': 'RSI divergence and extreme levels.',
          'roc': 'Rate-of-change slowdown signals.',
          'macd': 'Momentum divergence and crossovers.',
          'stochastic': 'Stochastic divergence patterns.',
          'williamsR': 'Williams %R reversal signals.',
          'cci': 'CCI divergence and momentum shifts.',
          'volume': 'Volume confirmation of reversal.',
          'adx': 'Trend weakening for reversal setup.',
          'priceMovement': 'Reversal candlestick patterns.',
        },
        enableDynamicPositionSizing: true,
        riskPerTrade: 0.015,
        stopLossPct: 1.5,
        takeProfitPct: 5.0,
        trailingStopEnabled: true,
        trailingStopAtrMultiplier: 2.0,
        autoExitEnabled: true,
        autoExitBufferMinutes: 20,
        allowContractRollover: false,
        skipRiskGuard: false,
        multiIntervalAnalysis: true,
      ),
      createdAt: DateTime.now(),
    ),
    FuturesStrategyTemplate(
      id: 'futures_time_of_day',
      name: 'Time-of-Day Momentum',
      description:
          'Capitalizes on intraday session patterns with time-based execution windows.',
      config: FuturesStrategyConfig(
        interval: '15m',
        minSignalStrength: 70.0,
        requireAllIndicatorsGreen: false,
        contractIds: ['ES', 'NQ', 'YM'],
        tradeQuantity: 1,
        maxContracts: 2,
        maxNotional: 150000.0,
        maxDailyLoss: 1200.0,
        sessionRules: const FuturesSessionRules(
          enforceTradingWindow: true,
          tradingWindowStart: '09:30',
          tradingWindowEnd: '11:30',
          allowOvernight: false,
          allowWeekend: false,
        ),
        enabledIndicators: {
          'priceMovement': true,
          'volume': true,
          'vwap': true,
          'momentum': true,
          'macd': true,
          'bollingerBands': true,
          'pivotPoints': true,
        },
        indicatorReasons: {
          'priceMovement': 'Intraday price action patterns.',
          'volume': 'Opening drive volume confirmation.',
          'vwap': 'Deviation from session value.',
          'momentum': 'RSI momentum during session.',
          'macd': 'Session momentum trends.',
          'bollingerBands': 'Intraday volatility bands.',
          'pivotPoints': 'Daily pivot level interactions.',
        },
        enableDynamicPositionSizing: true,
        riskPerTrade: 0.02,
        stopLossPct: 1.5,
        takeProfitPct: 4.0,
        trailingStopEnabled: true,
        trailingStopAtrMultiplier: 2.0,
        autoExitEnabled: true,
        autoExitBufferMinutes: 15,
        allowContractRollover: false,
        skipRiskGuard: false,
        multiIntervalAnalysis: false,
      ),
      createdAt: DateTime.now(),
    ),
  ];
}
